version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: clients
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "15432:5432"  # ← ICI tu exposes PostgreSQL en local (utile si tu veux t'y connecter avec DBeaver, pgAdmin, etc.)

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_NAME=clients
      - DB_USER=postgres
      - DB_PASSWORD=abc123
      - DB_HOST=db
    volumes:
      - .:/app
    command: ./wait-for-db.sh

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data:

