name: CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: clients
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: abc123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Initialize DB
        env:
          PGPASSWORD: abc123
        run: |
          psql -h localhost -U postgres -d clients -f ./db_init/init.sql

      - name: Run tests
        env:
          DB_NAME: clients
          DB_USER: postgres
          DB_PASSWORD: abc123
          DB_HOST: localhost
        run: |
          pytest
